apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-lybrary-pvc
  namespace: immich
spec:
  resources:
    requests:
      storage: 300Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
